spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#sql映射文件
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #  调整为自增主键
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000
#  打印日志
logging:
  level:
    com.tz.mall.ware: debug

