spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://101.35.249.158:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#sql映射文件
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #  调整为自增主键
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000
