spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
#        - 认证路由
#        - id: auth
#          uri: lb://auth-server
#          predicates:
#            - Path=/auth/**
#          filters:
#            - RewritePath=/auth/(?<segment>.*),/$\{segment}
#        商品API路由
        - id: product_route
          uri: lb://gulimall-product
          predicates:
           - Path=/api/product/**
          filters:
           - RewritePath=/api/(?<segment>.*),/$\{segment}
#        商品WEB路由
        - id: product_route_web
          uri: lb://gulimall-product
          predicates:
           - Path=/web/**
          filters:
           - RewritePath=/web/(?<segment>.*),/$\{segment}


#        商品web_Search路由
        - id: product_route_search
          uri: lb://gulimall-search
          predicates:
            - Path=/search/**
          filters:
            - RewritePath=/search/(?<segment>.*),/$\{segment}


#        会员路由
        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 仓储路由
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

#        第三方存储路由
        - id: third_party_route
          uri: lb://third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
           - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
            #  路径重写 将原先的 http://localhost:88/api/captcha.jpg?uuid
            #  重写为 http://localhost:8080/renren-fast/captcha.jpg -


#~~~~~~~~~~~~~~~~~~Nginx路由~~~~~~~~~~~~~~~~~~~~~~~~~
#        商品搜索 Nginx路由.
        - id: search_host
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com
#        登陆系统 Nginx路由.
        - id: auth_host
          uri: lb://auth-server
          predicates:
            - Host=auth.gulimall.com
#        购物车 Nginx路由.
        - id: cart_host
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com
#        订单 Nginx路由.
        - id: order_host
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com
#        会员 Nginx路由.
        - id: member_host
          uri: lb://gulimall-member
          predicates:
            - Host=member.gulimall.com
#        商品WEB Nginx路由.这段写在最后面，以防覆盖掉前面的其他配置路由
        - id: product_host
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com

  #gulimall-cart
  application:
    name: gulimall-gateway
server:
  port: 88